export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const UPDATE_PROJECT_TABLE_ROWS = "UPDATE_PROJECT_TABLE_ROWS"
export const LOAD_SELECTED_PROJECT = "LOAD_SELECTED_PROJECT"
export const UPDATE_PROJECT_TASKS_TABLE_ROWS = "UPDATE_PROJECT_TASKS_TABLE_ROWS"